name: CD Publish

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      test:
        description: 'Release to test?'
        required: false

env:
  UV_VERSION: 0.5.21
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: [ ubuntu-latest ]
    permissions:
      id-token: write
    steps:
      - name: Setup Local Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        run: |
          pip install --upgrade pip
          pip install "uv==$UV_VERSION"

      - name: Install and Build Package
        run: |
          uv sync
          uv build

      - name: Publish to PyPI
        if: "${{ github.event.inputs.test == '' }}"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PY_PI_TOKEN }}

      - name: Publish to Test PyPI
        if: "${{ github.event.inputs.test != '' }}"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PY_PI_TOKEN }}
