name: CD Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:


env:
  UV_VERSION: 0.5.21
  GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

jobs:
  build-and-release:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Setup Local Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Install uv
        run: |
          pip install --upgrade pip
          pip install "uv==$UV_VERSION"

      - name: Install Package
        run: uv sync

      - name: Increment Version
        run: uv run semantic-release version

  build-docs:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Setup Local Repo
        uses: actions/checkout@v3

      - name: Install uv
        run: |
          pip install --upgrade pip
          pip install "uv==$UV_VERSION"

      - name: Install Package
        run: uv sync

      - name: Build Docs
        run: uv run mkdocs gh-deploy --force
