name: Build dists and publish to PyPI and TestPyPI

on:
  release:
    types: [ published ]

env:
  UV_VERSION: 0.5.21
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Setup Local Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        run: |
          pip install --upgrade pip
          pip install "uv==$UV_VERSION"

      - name: Install and Build Package
        run: |
          uv sync
          uv build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-test-pypi:
    needs:
      - build
    runs-on: [ ubuntu-latest ]
    environment:
      name: testpypi
      url: https://test.pypi.org/p/kamae
    permissions:
      id-token: write
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-prod-pypi:
    needs:
      - build
    runs-on: [ ubuntu-latest ]
    environment:
      name: pypi
      url: https://pypi.org/p/kamae
    permissions:
      id-token: write
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to Prod PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
